[project]
name = "votando-no-ovo"
version = "0.1.0"
description = "Automatização do preenchimento e envio de um formulário de votação livre usando Python, Selenium e WebDriver Manager. "
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.2.2",
    "selenium>=4.43.0",
    "webdriver-manager>=4.0.2",
]
